# Generated by Django 3.2 on 2021-04-23 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SPZ', models.CharField(max_length=10)),
                ('Značka_typ_vozidla', models.CharField(max_length=100)),
                ('Počet_KM', models.IntegerField()),
                ('Datum_STK', models.DateField()),
            ],
        ),
    ]
