# Generated by Django 3.2 on 2021-04-23 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auto',
            old_name='Počet_KM',
            new_name='KM',
        ),
        migrations.RenameField(
            model_name='auto',
            old_name='Datum_STK',
            new_name='STK',
        ),
        migrations.RenameField(
            model_name='auto',
            old_name='Značka_typ_vozidla',
            new_name='Typ',
        ),
    ]
