# Generated by Django 3.2 on 2021-04-23 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0002_auto_20210423_0917'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zakaznik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Jmeno', models.CharField(max_length=30)),
                ('Prijmeni', models.CharField(max_length=30)),
                ('ČísloŘP', models.CharField(max_length=15)),
                ('Datum_narození', models.DateField()),
            ],
        ),
    ]
