# Generated by Django 3.2 on 2021-04-23 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0003_zakaznik'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vypujcka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Začátek', models.DateTimeField()),
                ('Cena', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='zakaznik',
            old_name='Jmeno',
            new_name='Jméno',
        ),
        migrations.RenameField(
            model_name='zakaznik',
            old_name='Prijmeni',
            new_name='Příjmení',
        ),
    ]
