# Generated by Django 3.2 on 2021-04-23 09:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0004_auto_20210423_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='vypujcka',
            name='Konec',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
